# Generated by Django 4.1 on 2022-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("PhoneNumber", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
    ]
