# Generated by Django 4.1 on 2022-08-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accapp", "0002_reach"),
    ]

    operations = [
        migrations.DeleteModel(name="Reach",),
    ]
