# Generated by Django 4.1 on 2022-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accapp", "0003_delete_reach"),
    ]

    operations = [
        migrations.CreateModel(
            name="reach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("PhoneNumber", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
    ]
