# Generated by Django 4.1 on 2022-08-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accapp", "0004_reach"),
    ]

    operations = [
        migrations.RenameModel(old_name="reach", new_name="reachus",),
    ]
