# Generated by Django 4.1 on 2022-08-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="grocery",),
    ]
